name: Update Backlog Status

on:
  #issue_comment:
  issues:
    types: [closed]

jobs:
  update-backlog:
    runs-on: ubuntu-latest

    steps:
    - name: Extract issue number
      id: extract_issue_number
      run: |
        issue_number=$(echo '${{ github.event.comment.body }}')
        echo "::set-output name=issue_number::$issue_number"
        issue_body=$(echo '${{ github.event.issue.body }}')
        echo "::set-output name=issue_body::$issue_body"
