name: Update Backlog Status

on:
  issue_comment:

jobs:
  update-backlog:
    runs-on: ubuntu-latest

    steps:
    - name: Check issue status
      id: check_status
      uses: actions/github-script@v6
      with:
        script: |
          const issue = context.payload.issue;
          return issue.state;
    
    - name: Extract issue number
      id: extract_issue_number
      run: |
        if [ "${{ github.event.action }}" == "closed" ]; then
          issue_number=$(echo '${{ github.event.comment.body }}')
          echo "::set-output name=issue_number::$issue_number"
          issue_body=$(echo '${{ github.event.issue.body }}')
          echo "::set-output name=issue_body::$issue_body"
        fi
